---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - image: alpine:3.18
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
    volumeMounts:
    - name: redis-data
      mountPath: /data
  restartPolicy: Always
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: redisdb-pvc
