---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  - name: prom
    protocol: TCP
    port: 9121
    targetPort: 9121
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2
        imagePullPolicy: Always
        args: ["--requirepass", "$(REDIS_PASSWORD)", "--appendonly", "no", "--save", "30", "100"]
        volumeMounts:
        - name: redis-data
          mountPath: /data
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-creds-dev
              key: REDIS_PASSWORD
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 15
          periodSeconds: 20
### redis exporter ###
#      - name: redis-exporter
#        image: oliver006/redis_exporter:latest
#        ports:
#          - containerPort: 9121
#            name: redis-exporter
#        env:
#          - name: REDIS_PASSWORD
#            valueFrom:
#              secretKeyRef:
#                key: REDIS_PASSWORD
#                name: app-creds-dev
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
#          limits:
#            cpu: 200m
#            memory: 200Mi
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redisdb-pvc
