---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.2.332
    hooks:
      - id: checkov
        args: [-d .]
#  - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
#    rev: v0.1.0
#    hooks:
#      - id: k8svalidate
#        files: .yaml$
#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.4.0
#    hooks:
#      - id: detect-secrets
