---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: tst
spec:
  type: NodePort
  ports:
  - port: 4369
    targetPort: 4369
    name: epmd
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: http
  selector:
    app: rabbitmq
