---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: rabbitmq-data-uat
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
#  namespace: develop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
