---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-dev-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  volumeMode: Filesystem
  hostPath:
    path: "/data"
