---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisdb-dev-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
